// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pointframe.Data.Context;

#nullable disable

namespace Pointframe.Data.Migrations
{
    [DbContext(typeof(PointframeDataContext))]
    [Migration("20260910041419_AddCaptureCatalog")]
    partial class AddCaptureCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Pointframe.Data.Entities.CaptureArtifactEntry", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("artifact_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_length");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("IndexedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at_utc");

                    b.Property<string>("IndexedSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_sha256");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LeaseExpiresUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_expires_utc");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_owner");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_attempt_utc");

                    b.Property<string>("OcrEngineVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("ocr_engine_version");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ocr_status");

                    b.Property<string>("OcrText")
                        .HasColumnType("TEXT")
                        .HasColumnName("ocr_text");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pixel_height");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pixel_width");

                    b.Property<string>("ProvenanceJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("provenance_json");

                    b.Property<string>("SearchTextNormalized")
                        .HasColumnType("TEXT")
                        .HasColumnName("search_text_normalized");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("TimestampSource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp_source");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ArtifactId");

                    b.HasIndex("Availability")
                        .HasDatabaseName("ix_capture_artifacts_availability");

                    b.HasIndex("CapturedAtUtc", "ArtifactId")
                        .HasDatabaseName("ix_capture_artifacts_captured_at_utc_artifact_id");

                    b.HasIndex("OcrStatus", "NextAttemptUtc")
                        .HasDatabaseName("ix_capture_artifacts_ocr_work");

                    b.ToTable("capture_artifacts", (string)null);
                });

            modelBuilder.Entity("Pointframe.Data.Entities.CaptureLocationEntry", b =>
                {
                    b.Property<string>("NormalizedPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_path");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_length");

                    b.Property<string>("CurrentArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_artifact_id");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<DateTime>("LastWriteAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_write_at_utc");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("original_path");

                    b.HasKey("NormalizedPath");

                    b.HasIndex("CurrentArtifactId")
                        .HasDatabaseName("ix_capture_locations_current_artifact_id");

                    b.ToTable("capture_locations", (string)null);
                });

            modelBuilder.Entity("Pointframe.Data.Entities.CaptureTextCacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_accessed_at");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("ix_capture_text_cache_file_path");

                    b.HasIndex("LastAccessedAt")
                        .HasDatabaseName("ix_capture_text_cache_last_accessed_at");

                    b.ToTable("capture_text_cache", (string)null);
                });

            modelBuilder.Entity("Pointframe.Data.Entities.CaptureLocationEntry", b =>
                {
                    b.HasOne("Pointframe.Data.Entities.CaptureArtifactEntry", "CurrentArtifact")
                        .WithMany("Locations")
                        .HasForeignKey("CurrentArtifactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentArtifact");
                });

            modelBuilder.Entity("Pointframe.Data.Entities.CaptureArtifactEntry", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
